### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ColaColin** [marcopompili/grunt-glsl#1]
Maybe I am just stupid, I have no idea at all what is wrong:

Creating library E:\Dev\git\physicsthing\frontend\node_modules\marcs-glsl-optimizer\build\Release\glslOptimizer.lib and object E:\Dev\git\physicsthing\fro
  ntend\node_modules\marcs-glsl-optimizer\build\Release\glslOptimizer.exp
glsl_optimizer_lib.lib(glsl_parser_extras.obj) : error LNK2001: unresolved external symbol "void __cdecl optimize_dead_builtin_variables(struct exec_list *,enu
m ir_variable_mode)" (?optimize_dead_builtin_variables@@YAXPEAUexec_list@@W4ir_variable_mode@@@Z) [E:\Dev\git\physicsthing\frontend\node_modules\marcs-glsl-opt
imizer\build\glslOptimizer.vcxproj]
glsl_optimizer_lib.lib(linker.obj) : error LNK2001: unresolved external symbol "bool __cdecl lower_vertex_id(struct gl_shader *)" (?lower_vertex_id@@YA_NPEAUgl
_shader@@@Z) [E:\Dev\git\physicsthing\frontend\node_modules\marcs-glsl-optimizer\build\glslOptimizer.vcxproj]
E:\Dev\git\physicsthing\frontend\node_modules\marcs-glsl-optimizer\build\Release\glslOptimizer.node : fatal error LNK1120: 2 unresolved externals [E:\Dev\git\p
hysicsthing\frontend\node_modules\marcs-glsl-optimizer\build\glslOptimizer.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ColaColin\AppData\Roaming\nvm\v5.4.1\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ColaColin\\AppData\\Roaming\\nvm\\v5.4.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\nod
e-gyp.js" "rebuild"
gyp ERR! cwd E:\Dev\git\physicsthing\frontend\node_modules\marcs-glsl-optimizer
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON neon-made-frontend@0.1.0 No description
npm WARN EPACKAGEJSON neon-made-frontend@0.1.0 No repository field.
npm WARN EPACKAGEJSON neon-made-frontend@0.1.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-glsl" "--save-dev"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! marcs-glsl-optimizer@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by marcopompili** [comment]
There's some linking problem on windows, I will check what's wrong.

**Comment by ColaColin** [comment]
I guess that's what I get for working on windows ^^
Thanks for looking into it.

**Comment by marcopompili** [comment]
Should be fine now, looks like the node gyp files were out of date.

Fixed by the commit on the npm package version 0.1.2 (https://www.npmjs.com/package/marcs-glsl-optimizer):

https://github.com/marcopompili/glsl-optimizer/commit/12e1ced198919093c1822ff3e97f379e33b60633
