### ISSUE TITLE
Insert result into exiting file rather than rewrite it

### ISSUE THREAD

**Issue by Danielhu229** [marcopompili/grunt-glsl#3]
Hi! I'm working my own webgl framework using your grunt task, and I have a global namespace like this

``` javascript
foo.bar = {
    ...
}
```

So the problem is, when I convert my glsl file to a js/ts file it rewrite the whole target file. What I really want is simply appending a variable statement at the end of target file, or more intelligently, find a exiting variable to assign the result(if not, create one).
for example

``` glsl
// .vert file
//#gljs varname:'foo.example'
...
```

``` javascript
// .js file
foo.bar = {
...
}
foo.example = {/* the source */}
```

or

``` glsl
// .vert file
//#gljs varname:'example'
...
```

``` javascript
// .js file
foo.bar = {
    var example = {/* the source */}
}
```

**Comment by marcopompili** [comment]
Hi Daniel,

The actual code generates simple variables and takes no account if those are actually present or not in the translated file, if I have time i would add this feature. Anyway you are more than welcome to try to help me out here with a pull request.

Not sure that I understand your problem, in this case how you are able to access the source code without a return call ?

```
// .js file
foo.bar = {
    var example = {/* the source */}
}
```

One thing that I think should be considered important, is that not to put program logic inside the translated js files. Instead I would use grunt.concat or grunt.uglify to concatenate the files, and then
elaborate you framework.

Anyway I would like to have more input from you about what problem are you facing with your framework.

M

**Comment by Danielhu229** [comment]
Sorry I have been busy all these days, but I 'd like to make a pull request soon.

the code you mentioned above is just a example, the final code will considered to be rely on replacing specific comments like
``` javascript
/* sometag */
```
the comment above will be replaced by generated result, so whether our code is logically correct will depend on user's logic, you can add 'var foo =' prefix or any other valid statement before the comment.
What do you think of that?Any advice?

**Comment by Danielhu229** [comment]
Yeah maybe concat or appending statement at the end of the file is better
The code you mentioned above is just a example, inserting statement into existing javascript logic is more complex, and there are several situations to consider.
I will soon make a pull request for that
